/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnswerOption = IDL.Record({
  'text' : IDL.Text,
  'feedbackText' : IDL.Opt(IDL.Text),
  'score' : IDL.Int,
});
export const Question = IDL.Record({
  'text' : IDL.Text,
  'scoreType' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(AnswerOption),
});
export const Section = IDL.Record({
  'heading' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const ClinicConfig = IDL.Record({
  'title' : IDL.Text,
  'customFields' : IDL.Vec(IDL.Text),
  'sections' : IDL.Vec(Section),
});
export const DemographicData = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'unitOfMeasure' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(IDL.Text),
  'gestationalAge' : IDL.Opt(IDL.Int),
});
export const TimestampType = IDL.Int;
export const Timestamp = IDL.Record({
  'followUp' : IDL.Opt(TimestampType),
  'recorded' : IDL.Opt(TimestampType),
  'submission' : TimestampType,
});
export const SubmissionStatus = IDL.Variant({
  'discarded' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PatientScore = IDL.Record({
  'obstructiveScore' : IDL.Opt(IDL.Int),
  'centralScore' : IDL.Opt(IDL.Int),
});
export const PatientAnswer = IDL.Record({
  'text' : IDL.Text,
  'optionIndex' : IDL.Nat,
  'score' : IDL.Int,
});
export const QuestionResponse = IDL.Record({
  'feedbackText' : IDL.Opt(IDL.Text),
  'answer' : PatientAnswer,
  'scoreType' : IDL.Opt(IDL.Text),
});
export const DetailedInfo = IDL.Record({
  'context' : IDL.Opt(IDL.Text),
  'date' : IDL.Opt(IDL.Text),
  'time' : IDL.Opt(IDL.Text),
});
export const PatientSubmission = IDL.Record({
  'id' : IDL.Nat,
  'additionalInfo' : IDL.Opt(IDL.Text),
  'patientId' : IDL.Opt(IDL.Text),
  'initialScore' : IDL.Record({ 'central' : IDL.Int, 'obstructive' : IDL.Int }),
  'clinicId' : IDL.Text,
  'demographic' : DemographicData,
  'feedbackCode' : IDL.Opt(IDL.Int),
  'timestamps' : IDL.Record({
    'followUp' : IDL.Opt(Timestamp),
    'recorded' : IDL.Opt(Timestamp),
    'submission' : Timestamp,
  }),
  'submissionStatus' : SubmissionStatus,
  'summary' : IDL.Record({
    'status' : SubmissionStatus,
    'score' : PatientScore,
  }),
  'responsesSectionA' : IDL.Vec(QuestionResponse),
  'responsesSectionB' : IDL.Vec(QuestionResponse),
  'notes' : IDL.Opt(IDL.Text),
  'detailedInfo' : DetailedInfo,
});
export const Professional = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ClinicMember = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateProfessional' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllClinicConfigs' : IDL.Func([], [IDL.Vec(ClinicConfig)], ['query']),
  'getAllDefaultClinicConfigs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ClinicConfig))],
      ['query'],
    ),
  'getAllPatientSubmissions' : IDL.Func(
      [],
      [IDL.Vec(PatientSubmission)],
      ['query'],
    ),
  'getAllProfessionals' : IDL.Func([], [IDL.Vec(Professional)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicConfig' : IDL.Func([IDL.Text], [IDL.Opt(ClinicConfig)], ['query']),
  'getClinicMembers' : IDL.Func([IDL.Text], [IDL.Vec(ClinicMember)], ['query']),
  'getDefaultClinicConfig' : IDL.Func([], [IDL.Opt(ClinicConfig)], ['query']),
  'getFilteredPatientSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PatientSubmission)],
      ['query'],
    ),
  'getPatientSubmission' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PatientSubmission)],
      ['query'],
    ),
  'getProfessional' : IDL.Func([IDL.Text], [IDL.Opt(Professional)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveClinicConfig' : IDL.Func([IDL.Text, ClinicConfig], [], []),
  'submitPatientForm' : IDL.Func([PatientSubmission], [IDL.Nat], []),
  'updateClinicMembers' : IDL.Func([IDL.Text, IDL.Vec(ClinicMember)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnswerOption = IDL.Record({
    'text' : IDL.Text,
    'feedbackText' : IDL.Opt(IDL.Text),
    'score' : IDL.Int,
  });
  const Question = IDL.Record({
    'text' : IDL.Text,
    'scoreType' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(AnswerOption),
  });
  const Section = IDL.Record({
    'heading' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const ClinicConfig = IDL.Record({
    'title' : IDL.Text,
    'customFields' : IDL.Vec(IDL.Text),
    'sections' : IDL.Vec(Section),
  });
  const DemographicData = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'unitOfMeasure' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(IDL.Text),
    'gestationalAge' : IDL.Opt(IDL.Int),
  });
  const TimestampType = IDL.Int;
  const Timestamp = IDL.Record({
    'followUp' : IDL.Opt(TimestampType),
    'recorded' : IDL.Opt(TimestampType),
    'submission' : TimestampType,
  });
  const SubmissionStatus = IDL.Variant({
    'discarded' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PatientScore = IDL.Record({
    'obstructiveScore' : IDL.Opt(IDL.Int),
    'centralScore' : IDL.Opt(IDL.Int),
  });
  const PatientAnswer = IDL.Record({
    'text' : IDL.Text,
    'optionIndex' : IDL.Nat,
    'score' : IDL.Int,
  });
  const QuestionResponse = IDL.Record({
    'feedbackText' : IDL.Opt(IDL.Text),
    'answer' : PatientAnswer,
    'scoreType' : IDL.Opt(IDL.Text),
  });
  const DetailedInfo = IDL.Record({
    'context' : IDL.Opt(IDL.Text),
    'date' : IDL.Opt(IDL.Text),
    'time' : IDL.Opt(IDL.Text),
  });
  const PatientSubmission = IDL.Record({
    'id' : IDL.Nat,
    'additionalInfo' : IDL.Opt(IDL.Text),
    'patientId' : IDL.Opt(IDL.Text),
    'initialScore' : IDL.Record({
      'central' : IDL.Int,
      'obstructive' : IDL.Int,
    }),
    'clinicId' : IDL.Text,
    'demographic' : DemographicData,
    'feedbackCode' : IDL.Opt(IDL.Int),
    'timestamps' : IDL.Record({
      'followUp' : IDL.Opt(Timestamp),
      'recorded' : IDL.Opt(Timestamp),
      'submission' : Timestamp,
    }),
    'submissionStatus' : SubmissionStatus,
    'summary' : IDL.Record({
      'status' : SubmissionStatus,
      'score' : PatientScore,
    }),
    'responsesSectionA' : IDL.Vec(QuestionResponse),
    'responsesSectionB' : IDL.Vec(QuestionResponse),
    'notes' : IDL.Opt(IDL.Text),
    'detailedInfo' : DetailedInfo,
  });
  const Professional = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ClinicMember = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateProfessional' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllClinicConfigs' : IDL.Func([], [IDL.Vec(ClinicConfig)], ['query']),
    'getAllDefaultClinicConfigs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ClinicConfig))],
        ['query'],
      ),
    'getAllPatientSubmissions' : IDL.Func(
        [],
        [IDL.Vec(PatientSubmission)],
        ['query'],
      ),
    'getAllProfessionals' : IDL.Func([], [IDL.Vec(Professional)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ClinicConfig)],
        ['query'],
      ),
    'getClinicMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClinicMember)],
        ['query'],
      ),
    'getDefaultClinicConfig' : IDL.Func([], [IDL.Opt(ClinicConfig)], ['query']),
    'getFilteredPatientSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PatientSubmission)],
        ['query'],
      ),
    'getPatientSubmission' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PatientSubmission)],
        ['query'],
      ),
    'getProfessional' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Professional)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveClinicConfig' : IDL.Func([IDL.Text, ClinicConfig], [], []),
    'submitPatientForm' : IDL.Func([PatientSubmission], [IDL.Nat], []),
    'updateClinicMembers' : IDL.Func([IDL.Text, IDL.Vec(ClinicMember)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };