/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerOption {
  'text' : string,
  'feedbackText' : [] | [string],
  'score' : bigint,
}
export interface ClinicConfig {
  'title' : string,
  'customFields' : Array<string>,
  'sections' : Array<Section>,
}
export interface ClinicMember {
  'id' : string,
  'contact' : string,
  'name' : string,
  'isActive' : boolean,
}
export interface DemographicData {
  'age' : [] | [bigint],
  'unitOfMeasure' : [] | [string],
  'gender' : [] | [string],
  'gestationalAge' : [] | [bigint],
}
export interface DetailedInfo {
  'context' : [] | [string],
  'date' : [] | [string],
  'time' : [] | [string],
}
export interface PatientAnswer {
  'text' : string,
  'optionIndex' : bigint,
  'score' : bigint,
}
export interface PatientScore {
  'obstructiveScore' : [] | [bigint],
  'centralScore' : [] | [bigint],
}
export interface PatientSubmission {
  'id' : bigint,
  'additionalInfo' : [] | [string],
  'patientId' : [] | [string],
  'initialScore' : { 'central' : bigint, 'obstructive' : bigint },
  'clinicId' : string,
  'demographic' : DemographicData,
  'feedbackCode' : [] | [bigint],
  'timestamps' : {
    'followUp' : [] | [Timestamp],
    'recorded' : [] | [Timestamp],
    'submission' : Timestamp,
  },
  'submissionStatus' : SubmissionStatus,
  'summary' : { 'status' : SubmissionStatus, 'score' : PatientScore },
  'responsesSectionA' : Array<QuestionResponse>,
  'responsesSectionB' : Array<QuestionResponse>,
  'notes' : [] | [string],
  'detailedInfo' : DetailedInfo,
  'personalInfo' : PersonalInfo,
}
export interface PersonalInfo {
  'country' : string,
  'medicalConditions' : string,
  'fullName' : string,
  'roomNumber' : string,
  'whatsappNumber' : string,
  'symptoms' : string,
}
export interface Professional {
  'id' : string,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
}
export interface Question {
  'text' : string,
  'scoreType' : [] | [string],
  'options' : Array<AnswerOption>,
}
export interface QuestionResponse {
  'feedbackText' : [] | [string],
  'answer' : PatientAnswer,
  'scoreType' : [] | [string],
}
export interface Section { 'heading' : string, 'questions' : Array<Question> }
export type SubmissionStatus = { 'discarded' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Timestamp {
  'followUp' : [] | [TimestampType],
  'recorded' : [] | [TimestampType],
  'submission' : TimestampType,
}
export type TimestampType = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateProfessional' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllClinicConfigs' : ActorMethod<[], Array<ClinicConfig>>,
  'getAllDefaultClinicConfigs' : ActorMethod<[], Array<[string, ClinicConfig]>>,
  'getAllPatientSubmissions' : ActorMethod<[], Array<PatientSubmission>>,
  'getAllProfessionals' : ActorMethod<[], Array<Professional>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicConfig' : ActorMethod<[string], [] | [ClinicConfig]>,
  'getClinicMembers' : ActorMethod<[string], Array<ClinicMember>>,
  'getDefaultClinicConfig' : ActorMethod<[], [] | [ClinicConfig]>,
  'getFilteredPatientSubmissions' : ActorMethod<
    [string],
    Array<PatientSubmission>
  >,
  'getPatientSubmission' : ActorMethod<[bigint], [] | [PatientSubmission]>,
  'getProfessional' : ActorMethod<[string], [] | [Professional]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveClinicConfig' : ActorMethod<[string, ClinicConfig], undefined>,
  'submitPatientForm' : ActorMethod<[PatientSubmission], bigint>,
  'updateClinicMembers' : ActorMethod<[string, Array<ClinicMember>], undefined>,
  'updatePatientPersonalInfo' : ActorMethod<[bigint, PersonalInfo], undefined>,
  'updatePatientSubmission' : ActorMethod<
    [bigint, PatientSubmission],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];