/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AnswerOption {
    text: string;
    feedbackText?: string;
    score: bigint;
}
export interface Timestamp {
    followUp?: TimestampType;
    recorded?: TimestampType;
    submission: TimestampType;
}
export interface PatientSubmission {
    id: bigint;
    additionalInfo?: string;
    patientId?: string;
    initialScore: {
        central: bigint;
        obstructive: bigint;
    };
    clinicId: string;
    demographic: DemographicData;
    feedbackCode?: bigint;
    timestamps: {
        followUp?: Timestamp;
        recorded?: Timestamp;
        submission: Timestamp;
    };
    submissionStatus: SubmissionStatus;
    summary: {
        status: SubmissionStatus;
        score: PatientScore;
    };
    responsesSectionA: Array<QuestionResponse>;
    responsesSectionB: Array<QuestionResponse>;
    notes?: string;
    detailedInfo: DetailedInfo;
    personalInfo: PersonalInfo;
}
export type TimestampType = bigint;
export interface DetailedInfo {
    context?: string;
    date?: string;
    time?: string;
}
export interface PersonalInfo {
    country: string;
    medicalConditions: string;
    fullName: string;
    roomNumber: string;
    whatsappNumber: string;
    symptoms: string;
}
export interface QuestionResponse {
    feedbackText?: string;
    answer: PatientAnswer;
    scoreType?: string;
}
export interface ClinicConfig {
    title: string;
    customFields: Array<string>;
    sections: Array<Section>;
}
export interface DemographicData {
    age?: bigint;
    unitOfMeasure?: string;
    gender?: string;
    gestationalAge?: bigint;
}
export interface PatientAnswer {
    text: string;
    optionIndex: bigint;
    score: bigint;
}
export interface Professional {
    id: string;
    name: string;
    role: string;
    isActive: boolean;
}
export interface Section {
    heading: string;
    questions: Array<Question>;
}
export interface PatientScore {
    obstructiveScore?: bigint;
    centralScore?: bigint;
}
export interface Question {
    text: string;
    scoreType?: string;
    options: Array<AnswerOption>;
}
export interface UserProfile {
    name: string;
}
export interface ClinicMember {
    id: string;
    contact: string;
    name: string;
    isActive: boolean;
}
export enum SubmissionStatus {
    discarded = "discarded",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateProfessional(id: string, name: string, role: string, isActive: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllClinicConfigs(): Promise<Array<ClinicConfig>>;
    getAllDefaultClinicConfigs(): Promise<Array<[string, ClinicConfig]>>;
    getAllPatientSubmissions(): Promise<Array<PatientSubmission>>;
    getAllProfessionals(): Promise<Array<Professional>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClinicConfig(clinicId: string): Promise<ClinicConfig | null>;
    getClinicMembers(clinicId: string): Promise<Array<ClinicMember>>;
    getDefaultClinicConfig(): Promise<ClinicConfig | null>;
    getFilteredPatientSubmissions(filterType: string): Promise<Array<PatientSubmission>>;
    getPatientSubmission(id: bigint): Promise<PatientSubmission | null>;
    getProfessional(id: string): Promise<Professional | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveClinicConfig(clinicId: string, config: ClinicConfig): Promise<void>;
    submitPatientForm(submission: PatientSubmission): Promise<bigint>;
    updateClinicMembers(clinicId: string, members: Array<ClinicMember>): Promise<void>;
    updatePatientPersonalInfo(submissionId: bigint, personalInfo: PersonalInfo): Promise<void>;
    updatePatientSubmission(submissionId: bigint, updatedSubmission: PatientSubmission): Promise<void>;
}
import type { AnswerOption as _AnswerOption, ClinicConfig as _ClinicConfig, DemographicData as _DemographicData, DetailedInfo as _DetailedInfo, PatientAnswer as _PatientAnswer, PatientScore as _PatientScore, PatientSubmission as _PatientSubmission, PersonalInfo as _PersonalInfo, Professional as _Professional, Question as _Question, QuestionResponse as _QuestionResponse, Section as _Section, SubmissionStatus as _SubmissionStatus, Timestamp as _Timestamp, TimestampType as _TimestampType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateProfessional(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProfessional(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProfessional(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllClinicConfigs(): Promise<Array<ClinicConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClinicConfigs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClinicConfigs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDefaultClinicConfigs(): Promise<Array<[string, ClinicConfig]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDefaultClinicConfigs();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDefaultClinicConfigs();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatientSubmissions(): Promise<Array<PatientSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientSubmissions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientSubmissions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfessionals(): Promise<Array<Professional>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfessionals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfessionals();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClinicConfig(arg0: string): Promise<ClinicConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicConfig(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicConfig(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClinicMembers(arg0: string): Promise<Array<ClinicMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicMembers(arg0);
            return result;
        }
    }
    async getDefaultClinicConfig(): Promise<ClinicConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultClinicConfig();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultClinicConfig();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredPatientSubmissions(arg0: string): Promise<Array<PatientSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredPatientSubmissions(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredPatientSubmissions(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientSubmission(arg0: bigint): Promise<PatientSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientSubmission(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientSubmission(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfessional(arg0: string): Promise<Professional | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfessional(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfessional(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveClinicConfig(arg0: string, arg1: ClinicConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveClinicConfig(arg0, to_candid_ClinicConfig_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveClinicConfig(arg0, to_candid_ClinicConfig_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitPatientForm(arg0: PatientSubmission): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPatientForm(to_candid_PatientSubmission_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPatientForm(to_candid_PatientSubmission_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateClinicMembers(arg0: string, arg1: Array<ClinicMember>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClinicMembers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClinicMembers(arg0, arg1);
            return result;
        }
    }
    async updatePatientPersonalInfo(arg0: bigint, arg1: PersonalInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientPersonalInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientPersonalInfo(arg0, arg1);
            return result;
        }
    }
    async updatePatientSubmission(arg0: bigint, arg1: PatientSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientSubmission(arg0, to_candid_PatientSubmission_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientSubmission(arg0, to_candid_PatientSubmission_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AnswerOption_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerOption): AnswerOption {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ClinicConfig_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClinicConfig): ClinicConfig {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_DemographicData_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DemographicData): DemographicData {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DetailedInfo_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetailedInfo): DetailedInfo {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PatientScore_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientScore): PatientScore {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PatientSubmission_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientSubmission): PatientSubmission {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionResponse_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionResponse): QuestionResponse {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Section_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Section): Section {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Timestamp_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Timestamp): Timestamp {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : from_candid_Timestamp_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimestampType]): TimestampType | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClinicConfig]): ClinicConfig | null {
    return value.length === 0 ? null : from_candid_ClinicConfig_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientSubmission]): PatientSubmission | null {
    return value.length === 0 ? null : from_candid_PatientSubmission_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Professional]): Professional | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    scoreType: [] | [string];
    options: Array<_AnswerOption>;
}): {
    text: string;
    scoreType?: string;
    options: Array<AnswerOption>;
} {
    return {
        text: value.text,
        scoreType: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.scoreType)),
        options: from_candid_vec_n13(_uploadFile, _downloadFile, value.options)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    feedbackText: [] | [string];
    score: bigint;
}): {
    text: string;
    feedbackText?: string;
    score: bigint;
} {
    return {
        text: value.text,
        feedbackText: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.feedbackText)),
        score: value.score
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    additionalInfo: [] | [string];
    patientId: [] | [string];
    initialScore: {
        central: bigint;
        obstructive: bigint;
    };
    clinicId: string;
    demographic: _DemographicData;
    feedbackCode: [] | [bigint];
    timestamps: {
        followUp: [] | [_Timestamp];
        recorded: [] | [_Timestamp];
        submission: _Timestamp;
    };
    submissionStatus: _SubmissionStatus;
    summary: {
        status: _SubmissionStatus;
        score: _PatientScore;
    };
    responsesSectionA: Array<_QuestionResponse>;
    responsesSectionB: Array<_QuestionResponse>;
    notes: [] | [string];
    detailedInfo: _DetailedInfo;
    personalInfo: _PersonalInfo;
}): {
    id: bigint;
    additionalInfo?: string;
    patientId?: string;
    initialScore: {
        central: bigint;
        obstructive: bigint;
    };
    clinicId: string;
    demographic: DemographicData;
    feedbackCode?: bigint;
    timestamps: {
        followUp?: Timestamp;
        recorded?: Timestamp;
        submission: Timestamp;
    };
    submissionStatus: SubmissionStatus;
    summary: {
        status: SubmissionStatus;
        score: PatientScore;
    };
    responsesSectionA: Array<QuestionResponse>;
    responsesSectionB: Array<QuestionResponse>;
    notes?: string;
    detailedInfo: DetailedInfo;
    personalInfo: PersonalInfo;
} {
    return {
        id: value.id,
        additionalInfo: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.additionalInfo)),
        patientId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.patientId)),
        initialScore: value.initialScore,
        clinicId: value.clinicId,
        demographic: from_candid_DemographicData_n21(_uploadFile, _downloadFile, value.demographic),
        feedbackCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.feedbackCode)),
        timestamps: from_candid_record_n25(_uploadFile, _downloadFile, value.timestamps),
        submissionStatus: from_candid_SubmissionStatus_n30(_uploadFile, _downloadFile, value.submissionStatus),
        summary: from_candid_record_n32(_uploadFile, _downloadFile, value.summary),
        responsesSectionA: from_candid_vec_n35(_uploadFile, _downloadFile, value.responsesSectionA),
        responsesSectionB: from_candid_vec_n35(_uploadFile, _downloadFile, value.responsesSectionB),
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes)),
        detailedInfo: from_candid_DetailedInfo_n38(_uploadFile, _downloadFile, value.detailedInfo),
        personalInfo: value.personalInfo
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    unitOfMeasure: [] | [string];
    gender: [] | [string];
    gestationalAge: [] | [bigint];
}): {
    age?: bigint;
    unitOfMeasure?: string;
    gender?: string;
    gestationalAge?: bigint;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.age)),
        unitOfMeasure: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.unitOfMeasure)),
        gender: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.gender)),
        gestationalAge: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.gestationalAge))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    followUp: [] | [_Timestamp];
    recorded: [] | [_Timestamp];
    submission: _Timestamp;
}): {
    followUp?: Timestamp;
    recorded?: Timestamp;
    submission: Timestamp;
} {
    return {
        followUp: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.followUp)),
        recorded: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.recorded)),
        submission: from_candid_Timestamp_n27(_uploadFile, _downloadFile, value.submission)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    followUp: [] | [_TimestampType];
    recorded: [] | [_TimestampType];
    submission: _TimestampType;
}): {
    followUp?: TimestampType;
    recorded?: TimestampType;
    submission: TimestampType;
} {
    return {
        followUp: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.followUp)),
        recorded: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.recorded)),
        submission: value.submission
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubmissionStatus;
    score: _PatientScore;
}): {
    status: SubmissionStatus;
    score: PatientScore;
} {
    return {
        status: from_candid_SubmissionStatus_n30(_uploadFile, _downloadFile, value.status),
        score: from_candid_PatientScore_n33(_uploadFile, _downloadFile, value.score)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    obstructiveScore: [] | [bigint];
    centralScore: [] | [bigint];
}): {
    obstructiveScore?: bigint;
    centralScore?: bigint;
} {
    return {
        obstructiveScore: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.obstructiveScore)),
        centralScore: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.centralScore))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feedbackText: [] | [string];
    answer: _PatientAnswer;
    scoreType: [] | [string];
}): {
    feedbackText?: string;
    answer: PatientAnswer;
    scoreType?: string;
} {
    return {
        feedbackText: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.feedbackText)),
        answer: value.answer,
        scoreType: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.scoreType))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    context: [] | [string];
    date: [] | [string];
    time: [] | [string];
}): {
    context?: string;
    date?: string;
    time?: string;
} {
    return {
        context: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.context)),
        date: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.date)),
        time: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.time))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    customFields: Array<string>;
    sections: Array<_Section>;
}): {
    title: string;
    customFields: Array<string>;
    sections: Array<Section>;
} {
    return {
        title: value.title,
        customFields: value.customFields,
        sections: from_candid_vec_n6(_uploadFile, _downloadFile, value.sections)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heading: string;
    questions: Array<_Question>;
}): {
    heading: string;
    questions: Array<Question>;
} {
    return {
        heading: value.heading,
        questions: from_candid_vec_n9(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ClinicConfig]): [string, ClinicConfig] {
    return [
        value[0],
        from_candid_ClinicConfig_n4(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discarded: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): SubmissionStatus {
    return "discarded" in value ? SubmissionStatus.discarded : "completed" in value ? SubmissionStatus.completed : "inProgress" in value ? SubmissionStatus.inProgress : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnswerOption>): Array<AnswerOption> {
    return value.map((x)=>from_candid_AnswerOption_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ClinicConfig]>): Array<[string, ClinicConfig]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientSubmission>): Array<PatientSubmission> {
    return value.map((x)=>from_candid_PatientSubmission_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClinicConfig>): Array<ClinicConfig> {
    return value.map((x)=>from_candid_ClinicConfig_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionResponse>): Array<QuestionResponse> {
    return value.map((x)=>from_candid_QuestionResponse_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Section>): Array<Section> {
    return value.map((x)=>from_candid_Section_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AnswerOption_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerOption): _AnswerOption {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_ClinicConfig_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClinicConfig): _ClinicConfig {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_DemographicData_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DemographicData): _DemographicData {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_DetailedInfo_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DetailedInfo): _DetailedInfo {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_PatientScore_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientScore): _PatientScore {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_PatientSubmission_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientSubmission): _PatientSubmission {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionResponse_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionResponse): _QuestionResponse {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_Section_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Section): _Section {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_Timestamp_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp): _Timestamp {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    customFields: Array<string>;
    sections: Array<Section>;
}): {
    title: string;
    customFields: Array<string>;
    sections: Array<_Section>;
} {
    return {
        title: value.title,
        customFields: value.customFields,
        sections: to_candid_vec_n48(_uploadFile, _downloadFile, value.sections)
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heading: string;
    questions: Array<Question>;
}): {
    heading: string;
    questions: Array<_Question>;
} {
    return {
        heading: value.heading,
        questions: to_candid_vec_n51(_uploadFile, _downloadFile, value.questions)
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    scoreType?: string;
    options: Array<AnswerOption>;
}): {
    text: string;
    scoreType: [] | [string];
    options: Array<_AnswerOption>;
} {
    return {
        text: value.text,
        scoreType: value.scoreType ? candid_some(value.scoreType) : candid_none(),
        options: to_candid_vec_n54(_uploadFile, _downloadFile, value.options)
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    feedbackText?: string;
    score: bigint;
}): {
    text: string;
    feedbackText: [] | [string];
    score: bigint;
} {
    return {
        text: value.text,
        feedbackText: value.feedbackText ? candid_some(value.feedbackText) : candid_none(),
        score: value.score
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    additionalInfo?: string;
    patientId?: string;
    initialScore: {
        central: bigint;
        obstructive: bigint;
    };
    clinicId: string;
    demographic: DemographicData;
    feedbackCode?: bigint;
    timestamps: {
        followUp?: Timestamp;
        recorded?: Timestamp;
        submission: Timestamp;
    };
    submissionStatus: SubmissionStatus;
    summary: {
        status: SubmissionStatus;
        score: PatientScore;
    };
    responsesSectionA: Array<QuestionResponse>;
    responsesSectionB: Array<QuestionResponse>;
    notes?: string;
    detailedInfo: DetailedInfo;
    personalInfo: PersonalInfo;
}): {
    id: bigint;
    additionalInfo: [] | [string];
    patientId: [] | [string];
    initialScore: {
        central: bigint;
        obstructive: bigint;
    };
    clinicId: string;
    demographic: _DemographicData;
    feedbackCode: [] | [bigint];
    timestamps: {
        followUp: [] | [_Timestamp];
        recorded: [] | [_Timestamp];
        submission: _Timestamp;
    };
    submissionStatus: _SubmissionStatus;
    summary: {
        status: _SubmissionStatus;
        score: _PatientScore;
    };
    responsesSectionA: Array<_QuestionResponse>;
    responsesSectionB: Array<_QuestionResponse>;
    notes: [] | [string];
    detailedInfo: _DetailedInfo;
    personalInfo: _PersonalInfo;
} {
    return {
        id: value.id,
        additionalInfo: value.additionalInfo ? candid_some(value.additionalInfo) : candid_none(),
        patientId: value.patientId ? candid_some(value.patientId) : candid_none(),
        initialScore: value.initialScore,
        clinicId: value.clinicId,
        demographic: to_candid_DemographicData_n59(_uploadFile, _downloadFile, value.demographic),
        feedbackCode: value.feedbackCode ? candid_some(value.feedbackCode) : candid_none(),
        timestamps: to_candid_record_n61(_uploadFile, _downloadFile, value.timestamps),
        submissionStatus: to_candid_SubmissionStatus_n64(_uploadFile, _downloadFile, value.submissionStatus),
        summary: to_candid_record_n66(_uploadFile, _downloadFile, value.summary),
        responsesSectionA: to_candid_vec_n69(_uploadFile, _downloadFile, value.responsesSectionA),
        responsesSectionB: to_candid_vec_n69(_uploadFile, _downloadFile, value.responsesSectionB),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        detailedInfo: to_candid_DetailedInfo_n72(_uploadFile, _downloadFile, value.detailedInfo),
        personalInfo: value.personalInfo
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    unitOfMeasure?: string;
    gender?: string;
    gestationalAge?: bigint;
}): {
    age: [] | [bigint];
    unitOfMeasure: [] | [string];
    gender: [] | [string];
    gestationalAge: [] | [bigint];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        unitOfMeasure: value.unitOfMeasure ? candid_some(value.unitOfMeasure) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        gestationalAge: value.gestationalAge ? candid_some(value.gestationalAge) : candid_none()
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    followUp?: Timestamp;
    recorded?: Timestamp;
    submission: Timestamp;
}): {
    followUp: [] | [_Timestamp];
    recorded: [] | [_Timestamp];
    submission: _Timestamp;
} {
    return {
        followUp: value.followUp ? candid_some(to_candid_Timestamp_n62(_uploadFile, _downloadFile, value.followUp)) : candid_none(),
        recorded: value.recorded ? candid_some(to_candid_Timestamp_n62(_uploadFile, _downloadFile, value.recorded)) : candid_none(),
        submission: to_candid_Timestamp_n62(_uploadFile, _downloadFile, value.submission)
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    followUp?: TimestampType;
    recorded?: TimestampType;
    submission: TimestampType;
}): {
    followUp: [] | [_TimestampType];
    recorded: [] | [_TimestampType];
    submission: _TimestampType;
} {
    return {
        followUp: value.followUp ? candid_some(value.followUp) : candid_none(),
        recorded: value.recorded ? candid_some(value.recorded) : candid_none(),
        submission: value.submission
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SubmissionStatus;
    score: PatientScore;
}): {
    status: _SubmissionStatus;
    score: _PatientScore;
} {
    return {
        status: to_candid_SubmissionStatus_n64(_uploadFile, _downloadFile, value.status),
        score: to_candid_PatientScore_n67(_uploadFile, _downloadFile, value.score)
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    obstructiveScore?: bigint;
    centralScore?: bigint;
}): {
    obstructiveScore: [] | [bigint];
    centralScore: [] | [bigint];
} {
    return {
        obstructiveScore: value.obstructiveScore ? candid_some(value.obstructiveScore) : candid_none(),
        centralScore: value.centralScore ? candid_some(value.centralScore) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    feedbackText?: string;
    answer: PatientAnswer;
    scoreType?: string;
}): {
    feedbackText: [] | [string];
    answer: _PatientAnswer;
    scoreType: [] | [string];
} {
    return {
        feedbackText: value.feedbackText ? candid_some(value.feedbackText) : candid_none(),
        answer: value.answer,
        scoreType: value.scoreType ? candid_some(value.scoreType) : candid_none()
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    context?: string;
    date?: string;
    time?: string;
}): {
    context: [] | [string];
    date: [] | [string];
    time: [] | [string];
} {
    return {
        context: value.context ? candid_some(value.context) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        time: value.time ? candid_some(value.time) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    discarded: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == SubmissionStatus.discarded ? {
        discarded: null
    } : value == SubmissionStatus.completed ? {
        completed: null
    } : value == SubmissionStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Section>): Array<_Section> {
    return value.map((x)=>to_candid_Section_n49(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n52(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AnswerOption>): Array<_AnswerOption> {
    return value.map((x)=>to_candid_AnswerOption_n55(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<QuestionResponse>): Array<_QuestionResponse> {
    return value.map((x)=>to_candid_QuestionResponse_n70(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
